### ISSUE TITLE
bg-image for landing page

### ISSUE THREAD

**Issue by claudioccm** [claudioccm/opennorth-website#5]
I added 4 images to rotate behind the "We create websites..." text. 
We need to rotate the images with fade-in/fade-out

**Comment by gmattar** [comment]
Transicoes em background-image não são especificadas pela w3c portanto não funcionam em alguns browsers, entre eles o firefox:

https://stackoverflow.com/questions/9483364/css3-background-image-transition

Sugiro utilizarmos uma grupo de < img >. O problema é que perderíamos a propriedade background-size: cover;

**Comment by claudioccm** [comment]
pensei em vc usar o mesmo JS q vc fez pro startupfarm. Aquilo q vc me
mostrou resolve
